#Logistic regression
* Find the `pima-diabetes.csv` file in the `./data/` folder.
* Can we correctly classify `Diabetes` or not knowing all the input variables?

In [18]:
from google.colab import files
uploaded = files.upload()
file_name = 'heart.csv'

Saving heart.csv to heart.csv


In [19]:
import pandas as pd
data = pd.read_csv(file_name, delimiter=',')
data.head()

age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1   37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2   41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3   56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4   57    0   0       120   354    0  ...      1      0.6      2   0     2       1

[5 rows x 14 columns]

In [0]:
import numpy as np
# Use np.loadtxt() instead when there are non-numeric values as well
dataset = np.genfromtxt(file_name, delimiter=",", skip_header = True)

In [21]:
np.set_printoptions(precision = 2) # does not work for too wide array
np.set_printoptions(formatter = {'float': '{: 0.1f}'.format})

print('')
print(dataset.shape)
print('')
print(dataset[0:5])


(303, 14)

[[ 63.0  1.0  3.0  145.0  233.0  1.0  0.0  150.0  0.0  2.3  0.0  0.0  1.0
   1.0]
 [ 37.0  1.0  2.0  130.0  250.0  0.0  1.0  187.0  0.0  3.5  0.0  0.0  2.0
   1.0]
 [ 41.0  0.0  1.0  130.0  204.0  0.0  0.0  172.0  0.0  1.4  2.0  0.0  2.0
   1.0]
 [ 56.0  1.0  1.0  120.0  236.0  0.0  1.0  178.0  0.0  0.8  2.0  0.0  2.0
   1.0]
 [ 57.0  0.0  0.0  120.0  354.0  0.0  1.0  163.0  1.0  0.6  2.0  0.0  2.0
   1.0]]


In [38]:
X = dataset[:, (0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13)]
Y = dataset[:, 1]
print(X)
print('')
print(Y)

[[ 63.0  3.0  145.0 ...  0.0  1.0  1.0]
 [ 37.0  2.0  130.0 ...  0.0  2.0  1.0]
 [ 41.0  1.0  130.0 ...  0.0  2.0  1.0]
 ...
 [ 68.0  0.0  144.0 ...  2.0  3.0  0.0]
 [ 57.0  0.0  130.0 ...  1.0  3.0  0.0]
 [ 57.0  1.0  130.0 ...  1.0  2.0  0.0]]

[ 1.0  1.0  0.0  1.0  0.0  1.0  0.0  1.0  1.0  1.0  1.0  0.0  1.0  1.0
  0.0  0.0  0.0  0.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0  0.0  1.0  1.0
  0.0  1.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0
  1.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0
  1.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  1.0  0.0  1.0  0.0
  1.0  1.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  1.0
  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  0.0  0.0  1.0  0.0  1.0
  1.0  1.0  1.0  1.0  0.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0
  0.0  1.0  1.0  0.0  1.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  1.0  1.0  1.0
  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1

In [0]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(1, input_dim = len(X[0, :]), activation='sigmoid'))

In [41]:
model.compile(loss='binary_crossentropy', optimizer = 'rmsprop', metrics=['accuracy'])
model.fit(X, Y, epochs = 1000, verbose = 0)

In [42]:
print ('True Validation Data:')
print(Y[:10])
prediction = model.predict(X)
print ('Prediction:')
print(prediction[0:10].T)

True Validation Data:
[ 1.0  1.0  0.0  1.0  0.0  1.0  0.0  1.0  1.0  1.0]
Prediction:
[[ 0.6  0.8  0.9  0.8  0.6  0.5  0.6  0.8  0.9  0.9]]


Are these predictions reasonable? Are they correct?