#Logistic regression
* Find the `pima-diabetes.csv` file in the `./data/` folder.
* Can we correctly classify `Diabetes` or not knowing all the input variables?

In [1]:
from google.colab import files
uploaded = files.upload()

Saving pima-diabetes.csv to pima-diabetes.csv


In [2]:
import pandas as pd
data = pd.read_csv('pima-diabetes.csv', delimiter=',')
data.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [0]:
import numpy as np
# Use np.loadtxt() instead when there are non-numeric values as well
dataset = np.genfromtxt('pima-diabetes.csv', delimiter=",", skip_header = True) 

In [4]:
np.set_printoptions(precision = 2) # does not work for too wide array
np.set_printoptions(formatter = {'float': '{: 0.1f}'.format})

print('')
print(dataset.shape)
print('')
print(dataset[0:5])


(768, 9)

[[ 6.0  148.0  72.0  35.0  0.0  33.6  0.6  50.0  1.0]
 [ 1.0  85.0  66.0  29.0  0.0  26.6  0.4  31.0  0.0]
 [ 8.0  183.0  64.0  0.0  0.0  23.3  0.7  32.0  1.0]
 [ 1.0  89.0  66.0  23.0  94.0  28.1  0.2  21.0  0.0]
 [ 0.0  137.0  40.0  35.0  168.0  43.1  2.3  33.0  1.0]]


In [12]:
X = dataset[:, :-1]
Y = dataset[:, -1]
print(X)
print('')
print(Y)

[[ 6.0  148.0  72.0 ...  33.6  0.6  50.0]
 [ 1.0  85.0  66.0 ...  26.6  0.4  31.0]
 [ 8.0  183.0  64.0 ...  23.3  0.7  32.0]
 ...
 [ 5.0  121.0  72.0 ...  26.2  0.2  30.0]
 [ 1.0  126.0  60.0 ...  30.1  0.3  47.0]
 [ 1.0  93.0  70.0 ...  30.4  0.3  23.0]]

[ 1.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0  1.0  1.0  0.0  1.0  0.0  1.0
  1.0  1.0  1.0  1.0  0.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  1.0  0.0
  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  0.0  0.0
  0.0  1.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0
  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0
  0.0  0.0  1.0  1.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0
  0.0  0.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
  0.0  0.0  0.0  1.0  0.0  0.0  0

In [0]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(1, input_dim = len(X[0, :]), activation='sigmoid'))

In [14]:
model.compile(loss='binary_crossentropy', optimizer = 'rmsprop', metrics=['accuracy'])
model.fit(X, Y, epochs = 256, verbose = 1)

Train on 768 samples
Epoch 1/256
768/768 [==============================] - 0s 92us/sample - loss: 17.5038 - acc: 0.4323
Epoch 2/256
768/768 [==============================] - 0s 36us/sample - loss: 16.7325 - acc: 0.4362
Epoch 3/256
768/768 [==============================] - 0s 34us/sample - loss: 16.0174 - acc: 0.4323
Epoch 4/256
768/768 [==============================] - 0s 37us/sample - loss: 15.2824 - acc: 0.4362
Epoch 5/256
768/768 [==============================] - 0s 39us/sample - loss: 14.5816 - acc: 0.4349
Epoch 6/256
768/768 [==============================] - 0s 32us/sample - loss: 13.9587 - acc: 0.4362
Epoch 7/256
768/768 [==============================] - 0s 33us/sample - loss: 13.2855 - acc: 0.4336
Epoch 8/256
768/768 [==============================] - 0s 36us/sample - loss: 12.6010 - acc: 0.4271
Epoch 9/256
768/768 [==============================] - 0s 33us/sample - loss: 11.9827 - acc: 0.4297
Epoch 10/256
768/768 [==============================] - 0s 31us/sample - loss: 

In [8]:
print ('True Validation Data:')
print(Y[:10])
prediction = model.predict(X)
print ('Prediction:')
print(prediction[0:10].T)

True Validation Data:
[ 1.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0  1.0  1.0]
Prediction:
[[ 0.4  0.1  0.7  0.1  0.6  0.2  0.2  0.8  0.4  0.1]]


Are these predictions reasonable? Are they correct?

In [11]:
acc = (0.6 + 0.1 + 0.3 + 0.1 + 0.4 + 0.2 + 0.8 + 0.6 + 0.9) * 10
print(100 - acc)
# Accuracy is low

60.0
